import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Card } from '../ui/Card';
import { InterviewQuestionEvaluation } from '../../types/interviewEvaluation';
export const InterviewQuestionReview = ({ evaluations }) => {
    if (!evaluations || evaluations.length === 0)
        return null;
    return (_jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: '1.5rem' }, children: evaluations.map((ev, i) => (_jsxs(Card, { style: { padding: '1.5rem' }, children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }, children: [_jsxs("h4", { style: { margin: 0, fontSize: '1rem', flex: 1, paddingRight: '1rem', color: 'var(--text-main)' }, children: [_jsxs("span", { style: { color: 'var(--primary)', marginRight: '0.5rem' }, children: ["Q", i + 1, "."] }), ev.question] }), ev.score !== undefined && ev.score !== null && (_jsxs("div", { style: { fontWeight: 'bold', color: 'var(--primary)', background: 'var(--bg-surface)', padding: '0.25rem 0.75rem', borderRadius: '1rem' }, children: [ev.score, "%"] }))] }), _jsxs("div", { style: { marginBottom: '1.5rem', background: 'var(--bg-main)', padding: '1rem', borderRadius: 'var(--radius-md)' }, children: [_jsx("div", { style: { fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }, children: "Your Answer:" }), _jsxs("div", { style: { fontStyle: 'italic' }, children: ["\"", ev.studentAnswer, "\""] })] }), ev.feedback && (_jsxs("div", { style: { marginBottom: '1rem' }, children: [_jsx("div", { style: { fontSize: '0.9rem', fontWeight: 500, marginBottom: '0.25rem' }, children: "Feedback:" }), _jsx("div", { style: { fontSize: '0.95rem' }, children: ev.feedback })] })), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginTop: '1rem', paddingTop: '1rem', borderTop: '1px solid var(--border-color)' }, children: [ev.strengths && ev.strengths.length > 0 && (_jsxs("div", { children: [_jsx("div", { style: { fontSize: '0.85rem', color: 'var(--success)', fontWeight: 'bold', marginBottom: '0.5rem' }, children: "What went well:" }), _jsx("ul", { style: { paddingLeft: '1.2rem', margin: 0, fontSize: '0.9rem' }, children: ev.strengths.map((s, idx) => _jsx("li", { children: s }, idx)) })] })), ev.improvementAreas && ev.improvementAreas.length > 0 && (_jsxs("div", { children: [_jsx("div", { style: { fontSize: '0.85rem', color: 'var(--warning)', fontWeight: 'bold', marginBottom: '0.5rem' }, children: "Focus Area:" }), _jsx("ul", { style: { paddingLeft: '1.2rem', margin: 0, fontSize: '0.9rem' }, children: ev.improvementAreas.map((a, idx) => _jsx("li", { children: a }, idx)) })] }))] })] }, ev.questionId || i))) }));
};
//# sourceMappingURL=InterviewQuestionReview.js.map