import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { ArrowLeft, CheckCircle, XCircle } from 'lucide-react';
export const JavaResultPage = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const result = location.state?.result;
    if (!result) {
        return (_jsxs("div", { style: { padding: '4rem', textAlign: 'center' }, children: ["No result data found.", _jsx("br", {}), _jsx(Button, { onClick: () => navigate('/technical/java'), style: { marginTop: '1rem' }, children: "Back to Dashboard" })] }));
    }
    const accuracy = Math.round((result.score / result.total) * 100) || 0;
    const incorrect = result.total - result.score;
    return (_jsxs("div", { style: { maxWidth: '600px', margin: '0 auto', padding: '2rem' }, children: [_jsx(Button, { variant: "ghost", icon: _jsx(ArrowLeft, { size: 16 }), onClick: () => navigate('/technical/java'), style: { marginBottom: '2rem' }, children: "Back to Java Programming" }), _jsxs("div", { style: { background: 'var(--bg-surface)', padding: '3rem', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-color)', textAlign: 'center' }, children: [_jsx("h1", { style: { fontSize: '2rem', marginBottom: '0.5rem' }, children: "Practice Complete" }), _jsxs("p", { style: { color: 'var(--text-secondary)', marginBottom: '2rem' }, children: ["Topic: ", _jsx("span", { style: { textTransform: 'capitalize', color: 'var(--text-main)' }, children: result.topic?.replace('_', ' ') })] }), _jsx("div", { style: { display: 'flex', justifyContent: 'center', marginBottom: '3rem' }, children: _jsx("div", { style: { position: 'relative', width: '150px', height: '150px', borderRadius: '50%', background: `conic-gradient(var(--primary) ${accuracy}%, var(--border-color) ${accuracy}%)`, display: 'flex', alignItems: 'center', justifyContent: 'center' }, children: _jsxs("div", { style: { position: 'absolute', width: '130px', height: '130px', background: 'var(--bg-surface)', borderRadius: '50%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }, children: [_jsxs("span", { style: { fontSize: '2rem', fontWeight: 700 }, children: [accuracy, "%"] }), _jsx("span", { style: { fontSize: '0.85rem', color: 'var(--text-secondary)' }, children: "Accuracy" })] }) }) }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '2rem' }, children: [_jsxs("div", { style: { background: 'rgba(34, 197, 94, 0.1)', border: '1px solid var(--success)', padding: '1rem', borderRadius: 'var(--radius-md)', display: 'flex', alignItems: 'center', gap: '1rem' }, children: [_jsx(CheckCircle, { size: 24, color: "var(--success)" }), _jsxs("div", { style: { textAlign: 'left' }, children: [_jsx("div", { style: { fontSize: '1.5rem', fontWeight: 600, color: 'var(--success)' }, children: result.score }), _jsx("div", { style: { fontSize: '0.85rem', color: 'var(--text-secondary)' }, children: "Correct" })] })] }), _jsxs("div", { style: { background: 'rgba(239, 68, 68, 0.1)', border: '1px solid var(--error)', padding: '1rem', borderRadius: 'var(--radius-md)', display: 'flex', alignItems: 'center', gap: '1rem' }, children: [_jsx(XCircle, { size: 24, color: "var(--error)" }), _jsxs("div", { style: { textAlign: 'left' }, children: [_jsx("div", { style: { fontSize: '1.5rem', fontWeight: 600, color: 'var(--error)' }, children: incorrect }), _jsx("div", { style: { fontSize: '0.85rem', color: 'var(--text-secondary)' }, children: "Incorrect" })] })] })] }), _jsx(Button, { variant: "primary", size: "lg", fullWidth: true, onClick: () => navigate('/technical/java'), children: "Continue Learning" })] })] }));
};
//# sourceMappingURL=JavaResultPage.js.map