from fastapi import APIRouter
from app.api.v1.endpoints import health, communication, fluency, formal, situational, group_discussion, aptitude, puzzle, code_execution, technical, technical_c, technical_cpp, technical_java, technical_python, technical_cs_core, assessments, interview, placement, resume, resume_improvement, student_analytics, recommendations, competitions, admin

api_router = APIRouter()
api_router.include_router(health.router, tags=["Health"])
api_router.include_router(communication.router, prefix="/v1/communication", tags=["Communication"])
api_router.include_router(fluency.router, prefix="/v1/communication/fluency", tags=["Fluency"])
api_router.include_router(formal.router, prefix="/v1/communication/formal", tags=["Formal Communication"])
api_router.include_router(situational.router, prefix="/v1/communication/situational", tags=["Situational Communication"])
api_router.include_router(group_discussion.router, prefix="/v1/communication/group-discussion", tags=["Group Discussion"])
api_router.include_router(aptitude.router, prefix="/v1/aptitude", tags=["Aptitude"])
api_router.include_router(puzzle.router, prefix="/v1/puzzles", tags=["Puzzles"])
api_router.include_router(code_execution.router, prefix="/v1/code", tags=["Code Execution"])
api_router.include_router(technical.router, prefix="/v1/technical", tags=["Technical"])
api_router.include_router(technical_c.router, prefix="/v1/technical/c", tags=["Technical C Programming"])
api_router.include_router(technical_cpp.router, prefix="/v1/technical/cpp", tags=["Technical C++ Programming"])
api_router.include_router(technical_java.router, prefix="/v1/technical/java", tags=["Technical Java Programming"])
api_router.include_router(technical_python.router, prefix="/v1/technical/python", tags=["Technical Python Programming"])
api_router.include_router(technical_cs_core.router, prefix="/v1/technical/cs-core", tags=["Technical CS Core"])
api_router.include_router(assessments.router, prefix="/v1/assessments", tags=["Assessments"])
api_router.include_router(interview.router, prefix="/v1/interviews", tags=["AI Interview Engine"])
api_router.include_router(placement.router, prefix="/v1/placement", tags=["Placement Simulation"])
api_router.include_router(resume.router, prefix="/v1/resumes", tags=["Resume Upload"])
api_router.include_router(resume_improvement.router, prefix="/v1/resume-improvement", tags=["Resume Improvement"])
api_router.include_router(admin.router, prefix="/v1/admin", tags=["Admin"])
api_router.include_router(student_analytics.router, prefix="/v1/analytics", tags=["Student Analytics"])
api_router.include_router(recommendations.router, prefix="/v1/recommendations", tags=["Recommendations"])
api_router.include_router(competitions.router, prefix="/v1/competitions", tags=["Competitions"])
